### ISSUE TITLE
installing argo

### ISSUE THREAD

**Issue by sundayoyeniyi** [albertosantini/argo#1]
Hi Albertosantini

I have fork and cloned the argo repo locally and trying to do "npm install" from within the directory where I cloned the repo into.  I am getting an error stating the rebuild failed at "node-svm@2.1.4 install script".  Its like its a problem with the node-svm package.

Can you please guide towards a solution so I can grunt serve this tool locally and take a look at your work?

Thanks

SO

**Comment by albertosantini** [comment]
Short answer (ignoring the build error about `node-svm`): `$ npm start`

Long story. :)

If you are an end-user, after installing `Node.js`, it is enough to follow the steps in `Getting Started`:

- `$ npm install -g argo-trading`
- `$ argo-trading`
- Eventually point your web brower to `http://localhost:8000`

Those steps install locally `argo-trading` (on Windows or Linux box).

Alternatively, after installing `Node.js`, cloning the repo (as you did), you may execute the following commands from the folder project:

- `$ npm install --production`
- `$ npm start`
- Eventually point your web brower to `http://localhost:8000`

A few notes from  a developer point of view.

Generally speaking, `node-svm` is a package you need to compile it.
However `node-svm` is used only in the experimental code and, even if it is not installed because the build fails (definitely, you can ignore the errors about `node-svm`), `argo-trading` works without it.

So, even if you have not installed a compiler, you can run the app and you can contribute to the project.

Eventually, of course, it is mandatory an OANDA account and an API token.

**Comment by sundayoyeniyi** [comment]
npm start works!

thanks.  

I'll dig around the source and return later.

SO.

**Comment by albertosantini** [comment]
Thanks for the feedback.

Feel free to open a new issue about doubts, questions, change requests or issues.
