### ISSUE TITLE
$ argo-trading : No such file or directory

### ISSUE THREAD

**Issue by magick93** [albertosantini/argo#6]
hello

I have installed Argo using `npm install -g argo-trading` - and it installs like normal npm applications.

But when I try to run it, using `argo-trading` I just get:

`No such file or directory`

Other node apps such as grunt and yo are working.

Any idea what I am doing wrong?

Im using Ubuntu 15.04

**Comment by albertosantini** [comment]
Thanks for the feedback.

If you give a look at the closed issues, there was a past issue about end of line, because the script contained Windows end of line. It seems this is not the case.

The shebang command `#!/usr/bin/env node` is the same used in the commands you said you installed, for instance `yo`. So I would discard it as the root of the problem, but, just in case, you may check it.

Another reason might be the executable permission: please, check if the command `argo-trading` is executable, with permissions `775`. 

If this is the reason, please, as workaround, fix it manually and if you confirm it, I would try to fix in the next major release.

**Comment by albertosantini** [comment]
Published v3.8.0 with the fix.
